backend:
  name: github
  repo: cole-wilson/cole-wilson.github.io # Path to your GitHub repository

media_folder: "img"

display_url: https://colewilson.xyz
logo_url: https://colewilson.xyz/apple-touch-icon.png

publish_mode: editorial_workflow
show_preview_links: true
preview_path: {{slug}}

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    label_singular: 'Post'
    description: >
      Blog posts and tutorials go here
    folder: "_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Description", name: "desc", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    label_singular: 'Page'
    description: >
      Individual pages go here.
    editor:
      preview: false
    folder: "_pages/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string", default: ""}
      - {label: "Layout", name: "layout", widget: "select", options: ["post", "page", "home", "project", "master", "archive"], default: ["page"]}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", required: false, name: "tags", widget: "list"}
      - {label: "Description", name: "desc", widget: "string"}
      - {label: "Overide Subtitle", name: "overidesub", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}
      
  - name: "projects" # Used in routes, e.g., /admin/collections/blog
    label: "Projects" # Used in the UI
    label_singular: 'Project'
    description: >
      Projects go here.
    editor:
      preview: false
    folder: "_projects/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", required: false, name: "tags", widget: "list"}
      - {label: "Description", name: "desc", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
#       - {label: "Related Post", name: "post", widget: "relation", collection: "posts", searchFields: ["desc", "title"], valueField: "title", displayFields: ["title"]}
      - {label: "URL to Website", name: "site", required: false, widget: "string", pattern: ['https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)', "Must be a URL"]}
      - {label: "Repo", name: "repo", required: false, widget: "string"}
      - {label: "GitHub User", required: false, name: "user", widget: "string", default: "cole-wilson"}
      - {label: "Download URL", required: false, name: "download", widget: "string", pattern: ['https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)', "Must be a URL"]}
      - {label: "Body", name: "body", widget: "markdown"}
  
  - name: "urls" # Used in routes, e.g., /admin/collections/blog
    label: "Shortened URLs" # Used in the UI
    label_singular: 'URL'
    description: >
      Create shortened URLS!
    editor:
      preview: false
    summary: "{{key}}"
    folder: "_links/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Key", name: "key", required: true, widget: "string"}
      - {label: "Links to:", name: "u", required: true, widget: "string", pattern: ['https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)', "Must be a URL"]}
      - label: "Countries"
        name: "countries"
        widget: "select"
        multiple: true
        options:
          - { value:"A1", label:"ğŸ•¶ï¸ Anonymous Proxy" }
          - { value:"A2", label:"ğŸ›°ï¸ Satellite Provider" }
          - { value:"01", label:"â“ Other Country" }
          - { value:"AD", label:"ğŸ‡¦ğŸ‡© Andorra" }
          - { value:"AE", label:"ğŸ‡¦ğŸ‡ª United Arab Emirates" }
          - { value:"AF", label:"ğŸ‡¦ğŸ‡« Afghanistan" }
          - { value:"AG", label:"ğŸ‡¦ğŸ‡¬ Antigua and Barbuda" }
          - { value:"AI", label:"ğŸ‡¦ğŸ‡® Anguilla" }
          - { value:"AL", label:"ğŸ‡¦ğŸ‡± Albania" }
          - { value:"AM", label:"ğŸ‡¦ğŸ‡² Armenia" }
          - { value:"AO", label:"ğŸ‡¦ğŸ‡´ Angola" }
          - { value:"AQ", label:"ğŸ‡¦ğŸ‡¶ Antarctica" }
          - { value:"AR", label:"ğŸ‡¦ğŸ‡· Argentina" }
          - { value:"AS", label:"ğŸ‡¦ğŸ‡¸ American Samoa" }
          - { value:"AT", label:"ğŸ‡¦ğŸ‡¹ Austria" }
          - { value:"AU", label:"ğŸ‡¦ğŸ‡º Australia" }
          - { value:"AW", label:"ğŸ‡¦ğŸ‡¼ Aruba" }
          - { value:"AX", label:"ğŸ‡¦ğŸ‡½ Ã…land Islands" }
          - { value:"AZ", label:"ğŸ‡¦ğŸ‡¿ Azerbaijan" }
          - { value:"BA", label:"ğŸ‡§ğŸ‡¦ Bosnia and Herzegovina" }
          - { value:"BB", label:"ğŸ‡§ğŸ‡§ Barbados" }
          - { value:"BD", label:"ğŸ‡§ğŸ‡© Bangladesh" }
          - { value:"BE", label:"ğŸ‡§ğŸ‡ª Belgium" }
          - { value:"BF", label:"ğŸ‡§ğŸ‡« Burkina Faso" }
          - { value:"BG", label:"ğŸ‡§ğŸ‡¬ Bulgaria" }
          - { value:"BH", label:"ğŸ‡§ğŸ‡­ Bahrain" }
          - { value:"BI", label:"ğŸ‡§ğŸ‡® Burundi" }
          - { value:"BJ", label:"ğŸ‡§ğŸ‡¯ Benin" }
          - { value:"BL", label:"ğŸ‡§ğŸ‡± Saint BarthÃ©lemy" }
          - { value:"BM", label:"ğŸ‡§ğŸ‡² Bermuda" }
          - { value:"BN", label:"ğŸ‡§ğŸ‡³ Brunei Darussalam" }
          - { value:"BO", label:"ğŸ‡§ğŸ‡´ Bolivia" }
          - { value:"BQ", label:"ğŸ‡§ğŸ‡¶ Bonaire, Sint Eustatius and Saba" }
          - { value:"BR", label:"ğŸ‡§ğŸ‡· Brazil" }
          - { value:"BS", label:"ğŸ‡§ğŸ‡¸ Bahamas" }
          - { value:"BT", label:"ğŸ‡§ğŸ‡¹ Bhutan" }
          - { value:"BV", label:"ğŸ‡§ğŸ‡» Bouvet Island" }
          - { value:"BW", label:"ğŸ‡§ğŸ‡¼ Botswana" }
          - { value:"BY", label:"ğŸ‡§ğŸ‡¾ Belarus" }
          - { value:"BZ", label:"ğŸ‡§ğŸ‡¿ Belize" }
          - { value:"CA", label:"ğŸ‡¨ğŸ‡¦ Canada" }
          - { value:"CC", label:"ğŸ‡¨ğŸ‡¨ Cocos (Keeling) Islands" }
          - { value:"CD", label:"ğŸ‡¨ğŸ‡© Congo" }
          - { value:"CF", label:"ğŸ‡¨ğŸ‡« Central African Republic" }
          - { value:"CG", label:"ğŸ‡¨ğŸ‡¬ Congo" }
          - { value:"CH", label:"ğŸ‡¨ğŸ‡­ Switzerland" }
          - { value:"CI", label:"ğŸ‡¨ğŸ‡® CÃ´te D'Ivoire" }
          - { value:"CK", label:"ğŸ‡¨ğŸ‡° Cook Islands" }
          - { value:"CL", label:"ğŸ‡¨ğŸ‡± Chile" }
          - { value:"CM", label:"ğŸ‡¨ğŸ‡² Cameroon" }
          - { value:"CN", label:"ğŸ‡¨ğŸ‡³ China" }
          - { value:"CO", label:"ğŸ‡¨ğŸ‡´ Colombia" }
          - { value:"CR", label:"ğŸ‡¨ğŸ‡· Costa Rica" }
          - { value:"CU", label:"ğŸ‡¨ğŸ‡º Cuba" }
          - { value:"CV", label:"ğŸ‡¨ğŸ‡» Cape Verde" }
          - { value:"CW", label:"ğŸ‡¨ğŸ‡¼ CuraÃ§ao" }
          - { value:"CX", label:"ğŸ‡¨ğŸ‡½ Christmas Island" }
          - { value:"CY", label:"ğŸ‡¨ğŸ‡¾ Cyprus" }
          - { value:"CZ", label:"ğŸ‡¨ğŸ‡¿ Czech Republic" }
          - { value:"DE", label:"ğŸ‡©ğŸ‡ª Germany" }
          - { value:"DJ", label:"ğŸ‡©ğŸ‡¯ Djibouti" }
          - { value:"DK", label:"ğŸ‡©ğŸ‡° Denmark" }
          - { value:"DM", label:"ğŸ‡©ğŸ‡² Dominica" }
          - { value:"DO", label:"ğŸ‡©ğŸ‡´ Dominican Republic" }
          - { value:"DZ", label:"ğŸ‡©ğŸ‡¿ Algeria" }
          - { value:"EC", label:"ğŸ‡ªğŸ‡¨ Ecuador" }
          - { value:"EE", label:"ğŸ‡ªğŸ‡ª Estonia" }
          - { value:"EG", label:"ğŸ‡ªğŸ‡¬ Egypt" }
          - { value:"EH", label:"ğŸ‡ªğŸ‡­ Western Sahara" }
          - { value:"ER", label:"ğŸ‡ªğŸ‡· Eritrea" }
          - { value:"ES", label:"ğŸ‡ªğŸ‡¸ Spain" }
          - { value:"ET", label:"ğŸ‡ªğŸ‡¹ Ethiopia" }
          - { value:"FI", label:"ğŸ‡«ğŸ‡® Finland" }
          - { value:"FJ", label:"ğŸ‡«ğŸ‡¯ Fiji" }
          - { value:"FK", label:"ğŸ‡«ğŸ‡° Falkland Islands (Malvinas)" }
          - { value:"FM", label:"ğŸ‡«ğŸ‡² Micronesia" }
          - { value:"FO", label:"ğŸ‡«ğŸ‡´ Faroe Islands" }
          - { value:"FR", label:"ğŸ‡«ğŸ‡· France" }
          - { value:"GA", label:"ğŸ‡¬ğŸ‡¦ Gabon" }
          - { value:"GB", label:"ğŸ‡¬ğŸ‡§ United Kingdom" }
          - { value:"GD", label:"ğŸ‡¬ğŸ‡© Grenada" }
          - { value:"GE", label:"ğŸ‡¬ğŸ‡ª Georgia" }
          - { value:"GF", label:"ğŸ‡¬ğŸ‡« French Guiana" }
          - { value:"GG", label:"ğŸ‡¬ğŸ‡¬ Guernsey" }
          - { value:"GH", label:"ğŸ‡¬ğŸ‡­ Ghana" }
          - { value:"GI", label:"ğŸ‡¬ğŸ‡® Gibraltar" }
          - { value:"GL", label:"ğŸ‡¬ğŸ‡± Greenland" }
          - { value:"GM", label:"ğŸ‡¬ğŸ‡² Gambia" }
          - { value:"GN", label:"ğŸ‡¬ğŸ‡³ Guinea" }
          - { value:"GP", label:"ğŸ‡¬ğŸ‡µ Guadeloupe" }
          - { value:"GQ", label:"ğŸ‡¬ğŸ‡¶ Equatorial Guinea" }
          - { value:"GR", label:"ğŸ‡¬ğŸ‡· Greece" }
          - { value:"GS", label:"ğŸ‡¬ğŸ‡¸ South Georgia" }
          - { value:"GT", label:"ğŸ‡¬ğŸ‡¹ Guatemala" }
          - { value:"GU", label:"ğŸ‡¬ğŸ‡º Guam" }
          - { value:"GW", label:"ğŸ‡¬ğŸ‡¼ Guinea-Bissau" }
          - { value:"GY", label:"ğŸ‡¬ğŸ‡¾ Guyana" }
          - { value:"HK", label:"ğŸ‡­ğŸ‡° Hong Kong" }
          - { value:"HM", label:"ğŸ‡­ğŸ‡² Heard Island and Mcdonald Islands" }
          - { value:"HN", label:"ğŸ‡­ğŸ‡³ Honduras" }
          - { value:"HR", label:"ğŸ‡­ğŸ‡· Croatia" }
          - { value:"HT", label:"ğŸ‡­ğŸ‡¹ Haiti" }
          - { value:"HU", label:"ğŸ‡­ğŸ‡º Hungary" }
          - { value:"ID", label:"ğŸ‡®ğŸ‡© Indonesia" }
          - { value:"IE", label:"ğŸ‡®ğŸ‡ª Ireland" }
          - { value:"IL", label:"ğŸ‡®ğŸ‡± Israel" }
          - { value:"IM", label:"ğŸ‡®ğŸ‡² Isle of Man" }
          - { value:"IN", label:"ğŸ‡®ğŸ‡³ India" }
          - { value:"IO", label:"ğŸ‡®ğŸ‡´ British Indian Ocean Territory" }
          - { value:"IQ", label:"ğŸ‡®ğŸ‡¶ Iraq" }
          - { value:"IR", label:"ğŸ‡®ğŸ‡· Iran" }
          - { value:"IS", label:"ğŸ‡®ğŸ‡¸ Iceland" }
          - { value:"IT", label:"ğŸ‡®ğŸ‡¹ Italy" }
          - { value:"JE", label:"ğŸ‡¯ğŸ‡ª Jersey" }
          - { value:"JM", label:"ğŸ‡¯ğŸ‡² Jamaica" }
          - { value:"JO", label:"ğŸ‡¯ğŸ‡´ Jordan" }
          - { value:"JP", label:"ğŸ‡¯ğŸ‡µ Japan" }
          - { value:"KE", label:"ğŸ‡°ğŸ‡ª Kenya" }
          - { value:"KG", label:"ğŸ‡°ğŸ‡¬ Kyrgyzstan" }
          - { value:"KH", label:"ğŸ‡°ğŸ‡­ Cambodia" }
          - { value:"KI", label:"ğŸ‡°ğŸ‡® Kiribati" }
          - { value:"KM", label:"ğŸ‡°ğŸ‡² Comoros" }
          - { value:"KN", label:"ğŸ‡°ğŸ‡³ Saint Kitts and Nevis" }
          - { value:"KP", label:"ğŸ‡°ğŸ‡µ North Korea" }
          - { value:"KR", label:"ğŸ‡°ğŸ‡· South Korea" }
          - { value:"KW", label:"ğŸ‡°ğŸ‡¼ Kuwait" }
          - { value:"KY", label:"ğŸ‡°ğŸ‡¾ Cayman Islands" }
          - { value:"KZ", label:"ğŸ‡°ğŸ‡¿ Kazakhstan" }
          - { value:"LA", label:"ğŸ‡±ğŸ‡¦ Lao People's Democratic Republic" }
          - { value:"LB", label:"ğŸ‡±ğŸ‡§ Lebanon" }
          - { value:"LC", label:"ğŸ‡±ğŸ‡¨ Saint Lucia" }
          - { value:"LI", label:"ğŸ‡±ğŸ‡® Liechtenstein" }
          - { value:"LK", label:"ğŸ‡±ğŸ‡° Sri Lanka" }
          - { value:"LR", label:"ğŸ‡±ğŸ‡· Liberia" }
          - { value:"LS", label:"ğŸ‡±ğŸ‡¸ Lesotho" }
          - { value:"LT", label:"ğŸ‡±ğŸ‡¹ Lithuania" }
          - { value:"LU", label:"ğŸ‡±ğŸ‡º Luxembourg" }
          - { value:"LV", label:"ğŸ‡±ğŸ‡» Latvia" }
          - { value:"LY", label:"ğŸ‡±ğŸ‡¾ Libya" }
          - { value:"MA", label:"ğŸ‡²ğŸ‡¦ Morocco" }
          - { value:"MC", label:"ğŸ‡²ğŸ‡¨ Monaco" }
          - { value:"MD", label:"ğŸ‡²ğŸ‡© Moldova" }
          - { value:"ME", label:"ğŸ‡²ğŸ‡ª Montenegro" }
          - { value:"MF", label:"ğŸ‡²ğŸ‡« Saint Martin (French Part)" }
          - { value:"MG", label:"ğŸ‡²ğŸ‡¬ Madagascar" }
          - { value:"MH", label:"ğŸ‡²ğŸ‡­ Marshall Islands" }
          - { value:"MK", label:"ğŸ‡²ğŸ‡° Macedonia" }
          - { value:"ML", label:"ğŸ‡²ğŸ‡± Mali" }
          - { value:"MM", label:"ğŸ‡²ğŸ‡² Myanmar" }
          - { value:"MN", label:"ğŸ‡²ğŸ‡³ Mongolia" }
          - { value:"MO", label:"ğŸ‡²ğŸ‡´ Macao" }
          - { value:"MP", label:"ğŸ‡²ğŸ‡µ Northern Mariana Islands" }
          - { value:"MQ", label:"ğŸ‡²ğŸ‡¶ Martinique" }
          - { value:"MR", label:"ğŸ‡²ğŸ‡· Mauritania" }
          - { value:"MS", label:"ğŸ‡²ğŸ‡¸ Montserrat" }
          - { value:"MT", label:"ğŸ‡²ğŸ‡¹ Malta" }
          - { value:"MU", label:"ğŸ‡²ğŸ‡º Mauritius" }
          - { value:"MV", label:"ğŸ‡²ğŸ‡» Maldives" }
          - { value:"MW", label:"ğŸ‡²ğŸ‡¼ Malawi" }
          - { value:"MX", label:"ğŸ‡²ğŸ‡½ Mexico" }
          - { value:"MY", label:"ğŸ‡²ğŸ‡¾ Malaysia" }
          - { value:"MZ", label:"ğŸ‡²ğŸ‡¿ Mozambique" }
          - { value:"NA", label:"ğŸ‡³ğŸ‡¦ Namibia" }
          - { value:"NC", label:"ğŸ‡³ğŸ‡¨ New Caledonia" }
          - { value:"NE", label:"ğŸ‡³ğŸ‡ª Niger" }
          - { value:"NF", label:"ğŸ‡³ğŸ‡« Norfolk Island" }
          - { value:"NG", label:"ğŸ‡³ğŸ‡¬ Nigeria" }
          - { value:"NI", label:"ğŸ‡³ğŸ‡® Nicaragua" }
          - { value:"NL", label:"ğŸ‡³ğŸ‡± Netherlands" }
          - { value:"NO", label:"ğŸ‡³ğŸ‡´ Norway" }
          - { value:"NP", label:"ğŸ‡³ğŸ‡µ Nepal" }
          - { value:"NR", label:"ğŸ‡³ğŸ‡· Nauru" }
          - { value:"NU", label:"ğŸ‡³ğŸ‡º Niue" }
          - { value:"NZ", label:"ğŸ‡³ğŸ‡¿ New Zealand" }
          - { value:"OM", label:"ğŸ‡´ğŸ‡² Oman" }
          - { value:"PA", label:"ğŸ‡µğŸ‡¦ Panama" }
          - { value:"PE", label:"ğŸ‡µğŸ‡ª Peru" }
          - { value:"PF", label:"ğŸ‡µğŸ‡« French Polynesia" }
          - { value:"PG", label:"ğŸ‡µğŸ‡¬ Papua New Guinea" }
          - { value:"PH", label:"ğŸ‡µğŸ‡­ Philippines" }
          - { value:"PK", label:"ğŸ‡µğŸ‡° Pakistan" }
          - { value:"PL", label:"ğŸ‡µğŸ‡± Poland" }
          - { value:"PM", label:"ğŸ‡µğŸ‡² Saint Pierre and Miquelon" }
          - { value:"PN", label:"ğŸ‡µğŸ‡³ Pitcairn" }
          - { value:"PR", label:"ğŸ‡µğŸ‡· Puerto Rico" }
          - { value:"PS", label:"ğŸ‡µğŸ‡¸ Palestinian Territory" }
          - { value:"PT", label:"ğŸ‡µğŸ‡¹ Portugal" }
          - { value:"PW", label:"ğŸ‡µğŸ‡¼ Palau" }
          - { value:"PY", label:"ğŸ‡µğŸ‡¾ Paraguay" }
          - { value:"QA", label:"ğŸ‡¶ğŸ‡¦ Qatar" }
          - { value:"RE", label:"ğŸ‡·ğŸ‡ª RÃ©union" }
          - { value:"RO", label:"ğŸ‡·ğŸ‡´ Romania" }
          - { value:"RS", label:"ğŸ‡·ğŸ‡¸ Serbia" }
          - { value:"RU", label:"ğŸ‡·ğŸ‡º Russia" }
          - { value:"RW", label:"ğŸ‡·ğŸ‡¼ Rwanda" }
          - { value:"SA", label:"ğŸ‡¸ğŸ‡¦ Saudi Arabia" }
          - { value:"SB", label:"ğŸ‡¸ğŸ‡§ Solomon Islands" }
          - { value:"SC", label:"ğŸ‡¸ğŸ‡¨ Seychelles" }
          - { value:"SD", label:"ğŸ‡¸ğŸ‡© Sudan" }
          - { value:"SE", label:"ğŸ‡¸ğŸ‡ª Sweden" }
          - { value:"SG", label:"ğŸ‡¸ğŸ‡¬ Singapore" }
          - { value:"SH", label:"ğŸ‡¸ğŸ‡­ Saint Helena, Ascension and Tristan Da Cunha" }
          - { value:"SI", label:"ğŸ‡¸ğŸ‡® Slovenia" }
          - { value:"SJ", label:"ğŸ‡¸ğŸ‡¯ Svalbard and Jan Mayen" }
          - { value:"SK", label:"ğŸ‡¸ğŸ‡° Slovakia" }
          - { value:"SL", label:"ğŸ‡¸ğŸ‡± Sierra Leone" }
          - { value:"SM", label:"ğŸ‡¸ğŸ‡² San Marino" }
          - { value:"SN", label:"ğŸ‡¸ğŸ‡³ Senegal" }
          - { value:"SO", label:"ğŸ‡¸ğŸ‡´ Somalia" }
          - { value:"SR", label:"ğŸ‡¸ğŸ‡· Suriname" }
          - { value:"SS", label:"ğŸ‡¸ğŸ‡¸ South Sudan" }
          - { value:"ST", label:"ğŸ‡¸ğŸ‡¹ Sao Tome and Principe" }
          - { value:"SV", label:"ğŸ‡¸ğŸ‡» El Salvador" }
          - { value:"SX", label:"ğŸ‡¸ğŸ‡½ Sint Maarten (Dutch Part)" }
          - { value:"SY", label:"ğŸ‡¸ğŸ‡¾ Syrian Arab Republic" }
          - { value:"SZ", label:"ğŸ‡¸ğŸ‡¿ Swaziland" }
          - { value:"TC", label:"ğŸ‡¹ğŸ‡¨ Turks and Caicos Islands" }
          - { value:"TD", label:"ğŸ‡¹ğŸ‡© Chad" }
          - { value:"TF", label:"ğŸ‡¹ğŸ‡« French Southern Territories" }
          - { value:"TG", label:"ğŸ‡¹ğŸ‡¬ Togo" }
          - { value:"TH", label:"ğŸ‡¹ğŸ‡­ Thailand" }
          - { value:"TJ", label:"ğŸ‡¹ğŸ‡¯ Tajikistan" }
          - { value:"TK", label:"ğŸ‡¹ğŸ‡° Tokelau" }
          - { value:"TL", label:"ğŸ‡¹ğŸ‡± Timor-Leste" }
          - { value:"TM", label:"ğŸ‡¹ğŸ‡² Turkmenistan" }
          - { value:"TN", label:"ğŸ‡¹ğŸ‡³ Tunisia" }
          - { value:"TO", label:"ğŸ‡¹ğŸ‡´ Tonga" }
          - { value:"TR", label:"ğŸ‡¹ğŸ‡· Turkey" }
          - { value:"TT", label:"ğŸ‡¹ğŸ‡¹ Trinidad and Tobago" }
          - { value:"TV", label:"ğŸ‡¹ğŸ‡» Tuvalu" }
          - { value:"TW", label:"ğŸ‡¹ğŸ‡¼ Taiwan" }
          - { value:"TZ", label:"ğŸ‡¹ğŸ‡¿ Tanzania" }
          - { value:"UA", label:"ğŸ‡ºğŸ‡¦ Ukraine" }
          - { value:"UG", label:"ğŸ‡ºğŸ‡¬ Uganda" }
          - { value:"UM", label:"ğŸ‡ºğŸ‡² United States Minor Outlying Islands" }
          - { value:"US", label:"ğŸ‡ºğŸ‡¸ United States" }
          - { value:"UY", label:"ğŸ‡ºğŸ‡¾ Uruguay" }
          - { value:"UZ", label:"ğŸ‡ºğŸ‡¿ Uzbekistan" }
          - { value:"VA", label:"ğŸ‡»ğŸ‡¦ Vatican City" }
          - { value:"VC", label:"ğŸ‡»ğŸ‡¨ Saint Vincent and The Grenadines" }
          - { value:"VE", label:"ğŸ‡»ğŸ‡ª Venezuela" }
          - { value:"VG", label:"ğŸ‡»ğŸ‡¬ Virgin Islands, British" }
          - { value:"VI", label:"ğŸ‡»ğŸ‡® Virgin Islands, U.S." }
          - { value:"VN", label:"ğŸ‡»ğŸ‡³ Viet Nam" }
          - { value:"VU", label:"ğŸ‡»ğŸ‡º Vanuatu" }
          - { value:"WF", label:"ğŸ‡¼ğŸ‡« Wallis and Futuna" }
          - { value:"WS", label:"ğŸ‡¼ğŸ‡¸ Samoa" }
          - { value:"YE", label:"ğŸ‡¾ğŸ‡ª Yemen" }
          - { value:"YT", label:"ğŸ‡¾ğŸ‡¹ Mayotte" }
          - { value:"ZA", label:"ğŸ‡¿ğŸ‡¦ South Africa" }
          - { value:"ZM", label:"ğŸ‡¿ğŸ‡² Zambia" }
          - { value:"ZW", label:"ğŸ‡¿ğŸ‡¼ Zimbabwe" }
#   - name: 'settings'
#     label: 'Settings'
#     delete: false # Prevent users from deleting documents in this collection
#     editor:
#       preview: false
#     files:
#       - name: 'Jekyll Config File'
#         label: 'Jekyll Config File'
#         file: '_config.yml'
#         description: 'Jekyll Config File'
#         fields:
#           - { label: 'Edit', name: 'body', widget: 'code' }
      
